name: CI/CD - Patient Booking Proxy (Full Deployment)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for complete deployment (infrastructure + applications)'
        required: true
        default: 'alpha'
        type: choice
        options:
          - alpha
          - beta
          - preprod
          - demo
          - prod
      destroy:
        description: 'Destroy infrastructure (monitoring alerts only)'
        required: false
        default: false
        type: boolean
      migrate_state:
        description: 'Migrate state to new environment'
        required: false
        default: false
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest 
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      should-deploy: ${{ steps.set-env.outputs.should-deploy }}
    steps:
      - name: Set environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
            echo "should-deploy=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "should-deploy=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/development" ]; then
            echo "environment=alpha" >> $GITHUB_OUTPUT
            echo "should-deploy=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/grigore" ]; then
            echo "environment=alpha" >> $GITHUB_OUTPUT
            echo "should-deploy=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "environment=alpha" >> $GITHUB_OUTPUT
            echo "should-deploy=false" >> $GITHUB_OUTPUT
          else
            echo "environment=alpha" >> $GITHUB_OUTPUT
            echo "should-deploy=false" >> $GITHUB_OUTPUT
          fi